export const CATEGORIES = [
  { value: '', label: '-' }, // Keep 'Categorias' or 'Todas' based on preference
  { value: 'music', label: 'Música' },
  { value: 'art', label: 'Arte' },
  { value: 'theater', label: 'Teatro' },
  { value: 'dance', label: 'Danza' },
  { value: 'comedy', label: 'Comedia' },
  { value: 'workshop', label: 'Taller' },
  // Add other categories from EventDetailModal if they differ
  { value: 'conference', label: 'Conferencia' },
  { value: 'literature', label: 'Literatura' },
  { value: 'film', label: 'Cine' },
  { value: 'gastronomy', label: 'Gastronomía' },
  { value: 'kids', label: 'Infantil' },
  { value: 'community', label: 'Comunitario' },
  { value: 'technology', label: 'Tecnología' },
  { value: 'fashion', label: 'Moda' },
  { value: 'sports', label: 'Deportes' },
  { value: 'other', label: 'Otro' },
]

export const AMENITIES_OPTIONS = [
  'Parking',
  'Bar',
  'Escenario',
  'Snacks',
  'Comida',
  'Acceso discapacitados',
  'Wi-Fi',
  'Aire acondicionado',
  'Pet friendly',
  'Vestuario',
]

export const STATUS_FILTERS = [
  { value: 'all', label: 'Todos' },
  { value: 'active', label: 'Próximos' },
  { value: 'past', label: 'Pasados' },
  { value: 'suspended', label: 'Suspendidos' },
  { value: 'cancelled', label: 'Cancelados' },
]

export const COUNTRIES_AND_CITIES = {
  Bolivia: [
    'La Paz',
    'Santa Cruz',
    'Cochabamba',
    'Sucre',
    'Oruro',
    'Potosí',
    'Tarija',
    'Beni',
    'Cobija',
    'El Alto',
    'Quillacollo',
    'Sacaba',
  ],
  Argentina: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'San Miguel de Tucumán',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
    'Resistencia',
    'Santiago del Estero',
    'Corrientes',
    'Neuquén',
    'Posadas',
    'San Salvador de Jujuy',
    'Bahía Blanca',
    'Paraná',
    'Formosa',
    'San Luis',
    'La Rioja',
    'Catamarca',
    'Río Cuarto',
  ],
  Brazil: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'São Luís',
    'Natal',
    'Florianópolis',
  ],
  Colombia: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Ibagué',
    'Pasto',
    'Manizales',
    'Neiva',
    'Villavicencio',
  ],
  Peru: [
    'Lima',
    'Arequipa',
    'Trujillo',
    'Cusco',
    'Chiclayo',
    'Piura',
    'Iquitos',
    'Huancayo',
    'Tacna',
    'Cajamarca',
    'Ica',
    'Chimbote',
    'Pucallpa',
    'Huánuco',
  ],
  Chile: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Arica',
    'Chillán',
    'Puerto Montt',
    'Iquique',
    'Copiapó',
    'Osorno',
    'Valdivia',
  ],
  España: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma de Mallorca',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Granada',
    'Vigo',
    'Gijón',
  ],
  Paraguay: [
    'Asunción',
    'Ciudad del Este',
    'San Lorenzo',
    'Encarnación',
    'Luque',
    'Capiatá',
    'Lambaré',
    'Fernando de la Mora',
    'Limpio',
    'Ñemby',
    'Pedro Juan Caballero',
    'Concepción',
  ],
  Uruguay: [
    'Montevideo',
    'Salto',
    'Ciudad de la Costa',
    'Paysandú',
    'Las Piedras',
    'Rivera',
    'Maldonado',
    'Tacuarembó',
    'Melo',
    'Mercedes',
    'Artigas',
    'Minas',
  ],
  Ecuador: [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Machala',
    'Manta',
    'Portoviejo',
    'Ambato',
    'Riobamba',
    'Quevedo',
    'Loja',
    'Ibarra',
    'Esmeraldas',
    'Santo Domingo',
    'Milagro',
  ],
  México: [
    'Ciudad de México',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Ciudad Juárez',
    'Querétaro',
    'Mérida',
    'Cancún',
    'Toluca',
    'Acapulco',
    'Aguascalientes',
    'Hermosillo',
    'Mexicali',
    'Morelia',
    'Veracruz',
    'Oaxaca',
  ],
  Venezuela: [
    'Caracas',
    'Maracaibo',
    'Valencia',
    'Barquisimeto',
    'Maracay',
    'Ciudad Guayana',
    'Barcelona',
    'Maturín',
    'Petare',
    'Puerto La Cruz',
    'Mérida',
    'Cumaná',
    'San Cristóbal',
    'Ciudad Bolívar',
  ],
}
