export const CATEGORIES = [
  { value: '', label: '-' },
  { value: 'music', label: 'Música' },
  { value: 'art', label: 'Arte' },
  { value: 'theater', label: 'Teatro' },
  { value: 'dance', label: 'Danza' },
  { value: 'comedy', label: 'Comedia' },
  { value: 'workshop', label: 'Taller' },
  { value: 'conference', label: 'Conferencia' },
  { value: 'literature', label: 'Literatura' },
  { value: 'film', label: 'Cine' },
  { value: 'gastronomy', label: 'Gastronomía' },
  { value: 'kids', label: 'Infantil' },
  { value: 'community', label: 'Comunitario' },
  { value: 'technology', label: 'Tecnología' },
  { value: 'fashion', label: 'Moda' },
  { value: 'sports', label: 'Deportes' },
  { value: 'other', label: 'Otro' },
]

export const AMENITIES_OPTIONS = [
  'Parking',
  'Bar',
  'Escenario',
  'Snacks',
  'Comida',
  'Acceso discapacitados',
  'Wi-Fi',
  'Aire acondicionado',
  'Pet friendly',
  'Vestuario',
]

export const STATUS_FILTERS = [
  { value: 'all', label: 'Todos' },
  { value: 'active', label: 'Próximos' },
  { value: 'past', label: 'Pasados' },
  { value: 'suspended', label: 'Suspendidos' },
  { value: 'cancelled', label: 'Cancelados' },
]

export const COUNTRIES_AND_CITIES = [
  {
    code: 'BO',
    name: 'Bolivia',
    cities: [
      'La Paz',
      'Santa Cruz',
      'Cochabamba',
      'Sucre',
      'Oruro',
      'Potosí',
      'Tarija',
      'Beni',
      'Cobija',
      'El Alto',
      'Quillacollo',
      'Sacaba',
    ],
  },
  {
    code: 'ES',
    name: 'España',
    cities: [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Sevilla',
      'Zaragoza',
      'Málaga',
      'Murcia',
      'Palma de Mallorca',
      'Las Palmas',
      'Lugo',
      'Bilbao',
      'Alicante',
      'Córdoba',
      'Granada',
      'Vigo',
      'Gijón',
    ],
  },
  {
    code: 'AR',
    name: 'Argentina',
    cities: [
      'Buenos Aires',
      'Córdoba',
      'Rosario',
      'Mendoza',
      'La Plata',
      'San Miguel de Tucumán',
      'Mar del Plata',
      'Salta',
      'Santa Fe',
      'San Juan',
      'Resistencia',
      'Santiago del Estero',
      'Corrientes',
      'Neuquén',
      'Posadas',
      'San Salvador de Jujuy',
      'Bahía Blanca',
      'Paraná',
      'Formosa',
      'San Luis',
      'La Rioja',
      'Catamarca',
      'Río Cuarto',
    ],
  },
  {
    code: 'BR',
    name: 'Brasil',
    cities: [
      'São Paulo',
      'Rio de Janeiro',
      'Brasília',
      'Salvador',
      'Fortaleza',
      'Belo Horizonte',
      'Manaus',
      'Curitiba',
      'Recife',
      'Porto Alegre',
      'Belém',
      'Goiânia',
      'Guarulhos',
      'Campinas',
      'São Luís',
      'Natal',
      'Florianópolis',
    ],
  },
  {
    code: 'CO',
    name: 'Colombia',
    cities: [
      'Bogotá',
      'Medellín',
      'Cali',
      'Barranquilla',
      'Cartagena',
      'Cúcuta',
      'Bucaramanga',
      'Pereira',
      'Santa Marta',
      'Ibagué',
      'Pasto',
      'Manizales',
      'Neiva',
      'Villavicencio',
    ],
  },
  {
    code: 'PE',
    name: 'Perú',
    cities: [
      'Lima',
      'Arequipa',
      'Trujillo',
      'Cusco',
      'Chiclayo',
      'Piura',
      'Iquitos',
      'Huancayo',
      'Tacna',
      'Cajamarca',
      'Ica',
      'Chimbote',
      'Pucallpa',
      'Huánuco',
    ],
  },
  {
    code: 'CL',
    name: 'Chile',
    cities: [
      'Santiago',
      'Valparaíso',
      'Concepción',
      'La Serena',
      'Antofagasta',
      'Temuco',
      'Rancagua',
      'Talca',
      'Arica',
      'Chillán',
      'Puerto Montt',
      'Iquique',
      'Copiapó',
      'Osorno',
      'Valdivia',
    ],
  },
  {
    code: 'PY',
    name: 'Paraguay',
    cities: [
      'Asunción',
      'Ciudad del Este',
      'San Lorenzo',
      'Encarnación',
      'Luque',
      'Capiatá',
      'Lambaré',
      'Fernando de la Mora',
      'Limpio',
      'Ñemby',
      'Pedro Juan Caballero',
      'Concepción',
    ],
  },
  {
    code: 'UY',
    name: 'Uruguay',
    cities: [
      'Montevideo',
      'Salto',
      'Ciudad de la Costa',
      'Paysandú',
      'Las Piedras',
      'Rivera',
      'Maldonado',
      'Tacuarembó',
      'Melo',
      'Mercedes',
      'Artigas',
      'Minas',
    ],
  },
  {
    code: 'EC',
    name: 'Ecuador',
    cities: [
      'Quito',
      'Guayaquil',
      'Cuenca',
      'Machala',
      'Manta',
      'Portoviejo',
      'Ambato',
      'Riobamba',
      'Quevedo',
      'Loja',
      'Ibarra',
      'Esmeraldas',
      'Santo Domingo',
      'Milagro',
    ],
  },
  {
    code: 'MX',
    name: 'México',
    cities: [
      'Ciudad de México',
      'Guadalajara',
      'Monterrey',
      'Puebla',
      'Tijuana',
      'León',
      'Ciudad Juárez',
      'Querétaro',
      'Mérida',
      'Cancún',
      'Toluca',
      'Acapulco',
      'Aguascalientes',
      'Hermosillo',
      'Mexicali',
      'Morelia',
      'Veracruz',
      'Oaxaca',
    ],
  },
  {
    code: 'VE',
    name: 'Venezuela',
    cities: [
      'Caracas',
      'Maracaibo',
      'Valencia',
      'Barquisimeto',
      'Maracay',
      'Ciudad Guayana',
      'Barcelona',
      'Maturín',
      'Petare',
      'Puerto La Cruz',
      'Mérida',
      'Cumaná',
      'San Cristóbal',
      'Ciudad Bolívar',
    ],
  },
]

// --- Form Field Definitions ---

export const venueFormFields = {
  name: {
    type: 'text',
    label: 'Nombre del sitio',
    required: true,
  },
  logo: {
    type: 'image',
    label: 'Logo',
    accept: 'image/*',
  },
  description: {
    type: 'textarea',
    label: 'Descripción',
    rows: 4,
    required: true,
    maxlength: 999,
  },
  address: {
    type: 'text',
    label: 'Dirección',
    required: true,
  },
  city: {
    type: 'text',
    label: 'Ciudad',
    required: true,
    show: false, // Consider if these should be visible or handled differently
  },
  country: {
    type: 'text',
    label: 'País',
    required: true,
    show: false, // Consider if these should be visible or handled differently
  },
  capacity: {
    type: 'number',
    label: 'Capacidad (personas)',
    min: 1,
  },
  email: {
    type: 'email',
    label: 'Email de contacto',
    required: true,
    show: false, // Consider if these should be visible or handled differently
  },
  facebookUrl: {
    type: 'text',
    label: 'Página de Facebook',
    placeholder: 'https://facebook.com/tu_pagina',
    description: 'Opcional',
  },
  instagramUrl: {
    type: 'text',
    label: 'Perfil de Instagram',
    placeholder: 'https://instagram.com/tu_usuario',
    description: 'Opcional',
  },
  whatsappNumber: {
    type: 'tel',
    label: 'Número de WhatsApp',
    placeholder: '+1234567890 (Incluir código de país)',
    description:
      'Opcional (Incluir código de país ej. +591)',
  },
  location: {
    type: 'map',
    label: 'Ubicación',
    description: 'Selecciona el punto exacto de entrada',
  },
  amenities: {
    type: 'checkboxGroup',
    label: 'Comodidades',
    options: AMENITIES_OPTIONS, // Assumes AMENITIES_OPTIONS is defined above
  },
  photos: {
    type: 'photoGallery',
    label: 'Fotos',
    description: 'Máximo 5 fotos',
    maxPhotos: 5,
  },
}

export const eventFormFields = {
  title: {
    type: 'text',
    label: 'Título del evento',
    required: true,
    maxLength: 100,
  },
  category: {
    type: 'select',
    label: 'Categoría',
    required: true,
    options: CATEGORIES, // Assumes CATEGORIES is defined above
  },
  date: {
    type: 'datetime-local',
    label: 'Fecha y hora',
    required: true,
  },
  price: {
    type: 'number',
    label: 'Precio',
    min: 0,
    max: 999999,
    step: '1',
    description: 'Deja en 0 si es gratis',
  },
  currency: {
    type: 'select',
    label: 'Moneda',
    required: true,
    options: [
      { value: 'BOB', label: 'Bs (BOB)' },
      { value: 'USD', label: '$ (USD)' },
      { value: 'EUR', label: '€ (EUR)' },
      { value: 'GBP', label: '£ (GBP)' },
      { value: 'BRL', label: 'R$ (BRL)' },
      { value: 'ARS', label: '$ (ARS)' },
      { value: 'CLP', label: '$ (CLP)' },
      { value: 'COP', label: '$ (COP)' },
      { value: 'MXN', label: '$ (MXN)' },
      { value: 'PEN', label: 'S/ (PEN)' },
      { value: 'UYU', label: '$U (UYU)' },
      { value: 'PYG', label: '₲ (PYG)' },
    ],
  },
  ticketUrl: {
    type: 'text',
    label: 'URL de venta de entradas',
    description:
      'Opcional: URL donde se pueden comprar entradas',
  },
  description: {
    type: 'textarea',
    label: 'Descripción',
    rows: 3,
    required: true,
    maxlength: 999,
  },
  image: {
    type: 'image',
    label: 'Imagen',
    description: 'Imagen principal del evento',
    accept: 'image/*',
  },
  status: {
    type: 'select',
    label: 'Estado del evento',
    required: true,
    options: [
      { value: 'active', label: 'Activo' },
      { value: 'cancelled', label: 'Cancelado' },
      { value: 'suspended', label: 'Suspendido' },
    ],
  },
}
